version: '2'
services:
    qinglong:
      image: whyour/qinglong:latest
      volumes:
        - /project/sandbox/ql/data:/ql/data
      ports:
       - "0.0.0.0:5700:5700"
      environment:
        QlBaseUrl: '/'
      restart: always

    cloudflared:
      restart: always
      network_mode: host
      environment:
          - TZ=Asia/Shanghai
      command: tunnel --edge-ip-version auto --protocol quic --heartbeat-interval 10s run --token eyJhIjoiZDgwOWZiNjYxYzBmMWNlMGFlYWFjMmYyYjUwYjQyY2IiLCJ0IjoiYTI0MmM0YTktNzEyYS00ZmNjLTlkMDctZDgwNDM0MGE1YjJjIiwicyI6Ik5HVmpObVl6TlRNdFlUUmlNeTAwT1dabExUZ3daRGN0TTJabU5EaGpOREExTkRJeSJ9
      container_name: cloudflared
      image: cloudflare/cloudflared:latest
